@baseUrl = http://localhost:3000

@urlPath = api


###

GET {{baseUrl}}/{{urlPath}}/testing
Content-Type: application/json
Accept: application/json
withCredentials: true


###


POST {{baseUrl}}/{{urlPath}}/register
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "name": "Eldad",
    "surnames": "Mamo",
    "email":"eldadfikre456@gmail.com",
    "role":"Admin",
    "password": "123456"
}

###

POST {{baseUrl}}/{{urlPath}}/login
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "email":"eldadfikre456@gmail.com",
    "password": "123456"
}

